"""
Automated form layout validation tests.

Validates that every CRA form template has:
  1. All referenced screenshot images on disk
  2. All input coordinates within valid range [0, 100]%
  3. No duplicate (page, left, top) positions per form
  4. A minimum number of inputs (sanity check for incomplete pages)
  5. Coordinate precision (< 40% round-number guesses)
  6. Each form input within 15% of at least one real PDF field (where JSON exists)

Run with:  python -m pytest tests/test_form_layout.py -v
"""

from __future__ import annotations

import json
import math
import os
import re

import pytest
from bs4 import BeautifulSoup

# ── Paths ─────────────────────────────────────────────────────────────────────
_HERE         = os.path.dirname(__file__)
TEMPLATES_DIR = os.path.join(_HERE, "..", "app", "templates")
STATIC_DIR    = os.path.join(_HERE, "..", "app", "static")
FORMS_DIR     = os.path.join(STATIC_DIR, "forms")
SCREENSHOTS   = os.path.join(STATIC_DIR, "forms", "screenshots")

# ── Form registry ─────────────────────────────────────────────────────────────
FORM_TEMPLATES: dict[str, str] = {
    "t1":           "t1.html",
    "bc428":        "bc428.html",
    "schedule3":    "schedule3.html",
    "schedule5":    "schedule5.html",
    "schedule7":    "schedule7.html",
    "schedule8":    "schedule8.html",
    "schedule9":    "schedule9.html",
    "t777":         "t777.html",
    "t2209":        "t2209.html",
    "worksheet_fed":"worksheet_fed.html",
}

# JSON files with auto-extracted PDF field positions (generated by extract_fields.py)
PDF_FIELDS_JSON: dict[str, str] = {
    "schedule5":    "schedule5-fields.json",
    "schedule7":    "schedule7-fields.json",
    "schedule8":    "schedule8-fields.json",
    "t777":         "t777-fields.json",
    "t2209":        "t2209-fields.json",
    "worksheet_fed":"worksheet_fed-fields.json",
    # Auto-generated (more complete):
    "bc428":        "bc428-auto-fields.json",
    "t1":           "t1-auto-fields.json",
    "schedule3":    "schedule3-auto-fields.json",
    "schedule9":    "schedule9-auto-fields.json",
}

# Minimum total editable inputs expected per form
FORM_MIN_INPUTS: dict[str, int] = {
    "t1": 50, "bc428": 50, "schedule3": 20, "schedule5": 15,
    "schedule7": 15, "schedule8": 10, "schedule9": 15,
    "t777": 10, "t2209": 5, "worksheet_fed": 10,
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def parse_template(template_name: str) -> tuple[list[dict], list]:
    """Parse a Jinja2 template and return (inputs_list, page_elements_list).

    Each input dict has: id, page, img_src, left, top, width, height, readonly.
    """
    path = os.path.join(TEMPLATES_DIR, template_name)
    with open(path, encoding="utf-8") as fh:
        html = fh.read()
    # Strip Jinja2 tags so BeautifulSoup can parse properly
    html = re.sub(r"\{%.*?%\}", "", html, flags=re.DOTALL)
    html = re.sub(r"\{\{.*?\}\}", "JINJA_VAR", html, flags=re.DOTALL)

    soup = BeautifulSoup(html, "html.parser")
    pages = soup.find_all("div", class_="pdf-page")

    inputs: list[dict] = []
    for pg_idx, page in enumerate(pages):
        img = page.find("img")
        img_src = img.get("src", "") if img else ""

        for inp in page.find_all("input", class_="pdf-input"):
            style = inp.get("style", "")
            left_m  = re.search(r"left:([\d.]+)%",   style)
            top_m   = re.search(r"top:([\d.]+)%",    style)
            width_m = re.search(r"width:([\d.]+)%",  style)
            height_m= re.search(r"height:([\d.]+)%", style)
            if not (left_m and top_m):
                continue
            inputs.append({
                "id":       inp.get("id", ""),
                "page":     pg_idx + 1,
                "img_src":  img_src,
                "left":     float(left_m.group(1)),
                "top":      float(top_m.group(1)),
                "width":    float(width_m.group(1)) if width_m else None,
                "height":   float(height_m.group(1)) if height_m else None,
                "readonly": inp.has_attr("readonly"),
            })
    return inputs, pages


def is_round(val: float, step: float = 5.0) -> bool:
    """Return True if the value is a multiple of *step* (suggests a guess)."""
    return abs(val % step) < 0.11


def load_pdf_fields(form_key: str) -> list[dict] | None:
    """Load the extracted PDF field JSON for a form, or None if not available."""
    fname = PDF_FIELDS_JSON.get(form_key)
    if not fname:
        return None
    path = os.path.join(FORMS_DIR, fname)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    # Normalise both formats: list of dicts with {page, left, top} OR {rect: [x,y,w,h]}
    result: list[dict] = []
    for f in data:
        if not isinstance(f, dict):
            continue
        if "left" in f and "top" in f:
            result.append({"page": f.get("page", 1), "left": f["left"], "top": f["top"]})
        elif "rect" in f:
            # bc428_fields.json / t1_fields.json style: {page, rect:[x0,y0,x1,y1]}
            # rect coords are in points on a 612×792 page
            rect = f["rect"]
            if len(rect) >= 4:
                result.append({
                    "page": f.get("page", 1),
                    "left": rect[0] / 612 * 100,
                    "top":  rect[1] / 792 * 100,
                })
    return result if result else None


# ── Tests ─────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("form_key,tmpl", list(FORM_TEMPLATES.items()))
def test_screenshot_images_exist(form_key: str, tmpl: str) -> None:
    """Every <img> in a form template must point to an existing file."""
    path = os.path.join(TEMPLATES_DIR, tmpl)
    with open(path, encoding="utf-8") as fh:
        html = fh.read()
    # Find all image src values
    srcs = re.findall(r'src="[^"]*?/static/([^"]+\.png|[^"]+\.jpg|[^"]+\.svg)"', html)
    missing = []
    for rel in srcs:
        full = os.path.join(STATIC_DIR, rel.replace("/", os.sep))
        if not os.path.exists(full):
            missing.append(rel)
    assert not missing, f"{form_key}: missing image files:\n" + "\n".join(missing)


@pytest.mark.parametrize("form_key,tmpl", list(FORM_TEMPLATES.items()))
def test_coordinate_ranges(form_key: str, tmpl: str) -> None:
    """All input left/top percentages must be strictly within [0, 100]."""
    inputs, _ = parse_template(tmpl)
    errors = []
    for inp in inputs:
        for axis in ("left", "top"):
            v = inp[axis]
            if not (0 <= v <= 100):
                errors.append(f"{inp['id']}: {axis}={v} out of [0,100]")
    assert not errors, f"{form_key} coordinate errors:\n" + "\n".join(errors)


@pytest.mark.parametrize("form_key,tmpl", list(FORM_TEMPLATES.items()))
def test_no_duplicate_positions(form_key: str, tmpl: str) -> None:
    """No two inputs on the same page may have exactly the same (left, top)."""
    inputs, _ = parse_template(tmpl)
    seen: dict[tuple, str] = {}
    errors = []
    for inp in inputs:
        key = (inp["page"], inp["left"], inp["top"])
        if key in seen:
            errors.append(
                f"page {inp['page']} ({inp['left']},{inp['top']}): "
                f"{inp['id']} duplicates {seen[key]}"
            )
        else:
            seen[key] = inp["id"]
    assert not errors, f"{form_key} duplicate positions:\n" + "\n".join(errors)


@pytest.mark.parametrize("form_key,min_count", list(FORM_MIN_INPUTS.items()))
def test_minimum_input_count(form_key: str, min_count: int) -> None:
    """Each form must have at least a minimum number of pdf-input elements."""
    tmpl = FORM_TEMPLATES[form_key]
    inputs, _ = parse_template(tmpl)
    # count only inputs that have coordinates (excludes anchors and hidden helpers)
    assert len(inputs) >= min_count, (
        f"{form_key}: only {len(inputs)} inputs, expected >= {min_count}"
    )


@pytest.mark.parametrize("form_key,tmpl", list(FORM_TEMPLATES.items()))
def test_coordinate_precision(form_key: str, tmpl: str) -> None:
    """Fewer than 40% of inputs should have BOTH left AND top as multiples of 5.

    Coordinates that are round multiples of 5 (e.g., 20%, 25%, 30%) strongly
    suggest guessed positions rather than values extracted from the PDF.
    """
    inputs, _ = parse_template(tmpl)
    if len(inputs) < 5:
        pytest.skip(f"{form_key} has too few inputs to assess precision")
    round_count = sum(1 for i in inputs if is_round(i["left"]) and is_round(i["top"]))
    pct = round_count / len(inputs) * 100
    assert pct <= 40, (
        f"{form_key}: {round_count}/{len(inputs)} ({pct:.0f}%) inputs have "
        f"suspiciously round coordinates — likely guessed, not PDF-extracted"
    )


@pytest.mark.parametrize("form_key", list(PDF_FIELDS_JSON.keys()))
def test_inputs_near_pdf_fields(form_key: str) -> None:
    """HTML inputs should be within 15% Euclidean distance of a real PDF field.

    At most 30% of inputs for a form may fail this check.  Forms where the HTML
    page number doesn't align with the PDF page number are skipped gracefully.
    """
    tmpl = FORM_TEMPLATES.get(form_key)
    if not tmpl:
        pytest.skip(f"No template for {form_key}")

    pdf_fields = load_pdf_fields(form_key)
    if not pdf_fields:
        pytest.skip(f"No PDF field data for {form_key}")

    inputs, _ = parse_template(tmpl)
    if not inputs:
        pytest.skip(f"No inputs in {form_key} template")

    # Group PDF fields by page for fast lookup
    pdf_by_page: dict[int, list[tuple[float, float]]] = {}
    for f in pdf_fields:
        pdf_by_page.setdefault(f["page"], []).append((f["left"], f["top"]))

    mismatches: list[str] = []
    skipped = 0
    for inp in inputs:
        pg = inp["page"]
        if pg not in pdf_by_page:
            skipped += 1
            continue
        min_dist = min(
            math.sqrt((inp["left"] - px) ** 2 + (inp["top"] - py) ** 2)
            for px, py in pdf_by_page[pg]
        )
        if min_dist > 15:
            mismatches.append(
                f"  {inp['id']} page={pg} ({inp['left']:.1f},{inp['top']:.1f}) "
                f"— nearest PDF field: {min_dist:.1f}% away"
            )

    checked = len(inputs) - skipped
    if checked == 0:
        pytest.skip(f"{form_key}: no inputs shared pages with PDF fields")

    fail_rate = len(mismatches) / checked
    assert fail_rate <= 0.30, (
        f"{form_key}: {len(mismatches)}/{checked} inputs ({fail_rate*100:.0f}%) "
        f"are >15% from any PDF field:\n" + "\n".join(mismatches[:8])
    )
