#!/usr/bin/env bash
# CRA Tax Helper — Local Startup Script (Mac / Linux)
# Run once to set up and start the app:
#   chmod +x scripts/start-local.sh
#   ./scripts/start-local.sh

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo ""
echo "========================================"
echo "  CRA Tax Helper — Local Startup"
echo "========================================"
echo ""

# ── Check Docker is installed ────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker is not installed."
    echo ""
    echo "Please install Docker Desktop from:"
    echo "  https://www.docker.com/products/docker-desktop/"
    echo "After installing, run this script again."
    exit 1
fi

# ── Check Docker is running ──────────────────────────────────────────────────
if ! docker info &>/dev/null; then
    echo "ERROR: Docker is installed but not running."
    echo ""
    echo "Please start Docker Desktop, wait for it to fully load,"
    echo "then run this script again."
    exit 1
fi

echo "✔ Docker is running"

# ── Generate .env if it doesn't exist ───────────────────────────────────────
ENV_FILE="$ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo ""
    echo "First-time setup: generating encryption key..."

    KEY=""
    # Try Python (most systems have it)
    if command -v python3 &>/dev/null; then
        KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || true)
    fi
    if [ -z "$KEY" ] && command -v python &>/dev/null; then
        KEY=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || true)
    fi
    # Fallback: use openssl
    if [ -z "$KEY" ] && command -v openssl &>/dev/null; then
        KEY=$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=')=
    fi

    cat > "$ENV_FILE" <<EOF
# CRA Tax Helper — auto-generated by start-local.sh
# IMPORTANT: Keep this file private. Back it up somewhere safe.
# If you lose this key, your saved tax data cannot be decrypted.

FIELD_ENCRYPTION_KEY=$KEY
LOCAL_USER_NAME=Local User
LOCAL_USER_EMAIL=local@cra-helper.local
EOF

    echo "✔ Created .env with a unique encryption key"
    echo "  → Key saved to: $ENV_FILE"
    echo "  → Back up this file to keep your data safe!"
else
    echo "✔ Using existing .env file"
fi

# ── Build and start ──────────────────────────────────────────────────────────
echo ""
echo "Building and starting CRA Tax Helper..."
echo "(This may take a few minutes the first time)"
echo ""

docker compose up --build -d

# ── Wait for health check ────────────────────────────────────────────────────
echo ""
echo "Waiting for app to be ready..."
READY=false
for i in $(seq 1 20); do
    sleep 2
    if curl -sf http://localhost:8080/health >/dev/null 2>&1; then
        READY=true
        break
    fi
    echo "  Waiting... ($i/20)"
done

echo ""
if [ "$READY" = true ]; then
    echo "========================================"
    echo "  ✔ CRA Tax Helper is running!"
    echo "========================================"
    echo ""
    echo "  Open your browser and go to:"
    echo "  http://localhost:8080"
    echo ""
    echo "  To stop the app:  docker compose down"
    echo "  To view logs:     docker compose logs -f"
    echo ""
    # Try to open browser on Mac
    if command -v open &>/dev/null; then
        open http://localhost:8080
    # Try on Linux
    elif command -v xdg-open &>/dev/null; then
        xdg-open http://localhost:8080
    fi
else
    echo "App may still be starting. Try opening:"
    echo "  http://localhost:8080"
    echo ""
    echo "To view startup logs: docker compose logs taxhelper"
fi
