# CRA Tax Helper — Local Startup Script (Windows PowerShell)
# Run this once to set up and start the app.
# Double-click or right-click > "Run with PowerShell"

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  CRA Tax Helper — Local Startup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ── Check Docker is installed ────────────────────────────────────────────────
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: Docker is not installed or not on your PATH." -ForegroundColor Red
    Write-Host ""
    Write-Host "Please install Docker Desktop from https://www.docker.com/products/docker-desktop/" -ForegroundColor Yellow
    Write-Host "After installing, restart this script." -ForegroundColor Yellow
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

# ── Check Docker is running ──────────────────────────────────────────────────
$dockerRunning = docker info 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker is installed but not running." -ForegroundColor Red
    Write-Host ""
    Write-Host "Please start Docker Desktop, wait for it to fully load," -ForegroundColor Yellow
    Write-Host "then run this script again." -ForegroundColor Yellow
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host "✔ Docker is running" -ForegroundColor Green

# ── Generate .env if it doesn't exist ───────────────────────────────────────
$EnvFile = Join-Path $Root ".env"
if (-not (Test-Path $EnvFile)) {
    Write-Host ""
    Write-Host "First-time setup: generating encryption key..." -ForegroundColor Yellow

    # Generate a Fernet encryption key using Python (bundled with Docker image build)
    # We use Python directly here since it's likely installed on most dev machines
    $key = ""
    try {
        $key = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>$null
    } catch {}

    if (-not $key) {
        # Fallback: generate 32 random bytes and base64-encode (URL-safe)
        try {
            $bytes = New-Object byte[] 32
            [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
            $b64 = [Convert]::ToBase64String($bytes).Replace('+','-').Replace('/','_').TrimEnd('=')
            $key = $b64 + "="
        } catch {
            Write-Host "WARNING: Could not generate encryption key. Data will not be encrypted." -ForegroundColor Yellow
        }
    }

    $envContent = @"
# CRA Tax Helper — auto-generated by start-local.ps1
# IMPORTANT: Keep this file private. Back it up somewhere safe.
# If you lose this key, your saved tax data cannot be decrypted.

FIELD_ENCRYPTION_KEY=$key
LOCAL_USER_NAME=Local User
LOCAL_USER_EMAIL=local@cra-helper.local
"@
    Set-Content -Path $EnvFile -Value $envContent
    Write-Host "✔ Created .env with a unique encryption key" -ForegroundColor Green
    Write-Host "  → Key saved to: $EnvFile" -ForegroundColor DarkGray
    Write-Host "  → Back up this file to keep your data safe!" -ForegroundColor DarkYellow
} else {
    Write-Host "✔ Using existing .env file" -ForegroundColor Green
}

# ── Build and start ──────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Building and starting CRA Tax Helper..." -ForegroundColor Cyan
Write-Host "(This may take a few minutes the first time)" -ForegroundColor DarkGray
Write-Host ""

docker compose up --build -d

if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "ERROR: Failed to start. See above for details." -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

# ── Wait for health check ────────────────────────────────────────────────────
Write-Host ""
Write-Host "Waiting for app to be ready..." -ForegroundColor Cyan
$retries = 20
$ready = $false
for ($i = 0; $i -lt $retries; $i++) {
    Start-Sleep -Seconds 2
    try {
        $resp = Invoke-WebRequest -Uri "http://localhost:8080/health" -UseBasicParsing -TimeoutSec 3 -ErrorAction SilentlyContinue
        if ($resp.StatusCode -eq 200) {
            $ready = $true
            break
        }
    } catch {}
    Write-Host "  Waiting... ($($i+1)/$retries)" -ForegroundColor DarkGray
}

Write-Host ""
if ($ready) {
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "  ✔ CRA Tax Helper is running!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Open your browser and go to:" -ForegroundColor White
    Write-Host "  http://localhost:8080" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  To stop the app:  docker compose down" -ForegroundColor DarkGray
    Write-Host "  To view logs:     docker compose logs -f" -ForegroundColor DarkGray
    Write-Host ""
    # Try to open the browser automatically
    Start-Process "http://localhost:8080"
} else {
    Write-Host "App may still be starting. Try opening:" -ForegroundColor Yellow
    Write-Host "  http://localhost:8080" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "To view startup logs: docker compose logs taxhelper" -ForegroundColor DarkGray
}

Read-Host "Press Enter to exit"
